#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <log.h>

#include "init.h"
#include "add.h"
#include "remove.h"
#include "build.h"
#include "clean.h"
#include "config.h"
#include "run.h"


#define VERSION "v0.3.0"


int pm_help(int argc, char **argv);
int pm_version(int argc, char **argv);

typedef int (*CmdHandler)(int argc, char** argv);

/* Metadata used to match a command name with its implementation. */
typedef struct Command Command;
typedef struct Command {
  const char *name;
  const char *description;
  const char *usage;

  CmdHandler handler; 
} Command;

static const Command commands[] = {
    {"init", "make a directory with a project structure", "pm init <name>",
     pm_init},
    {"add", "add .h and .c files in the project", "pm add <name>", pm_add},
    {"rm", "remove .h and .c files in the project", "pm rm <name>", pm_remove},
    {"build", "build a pm project", "pm build [-v] [-p <project>]", pm_build},
    {"run", "run a pm project",
     "pm run [-v] [-b] [-p <project>] [target] [-a args...]", pm_run},
    {"clean", "remove files generated by the project Makefile",
     "pm clean [-v] [-p <project>]", pm_clean},
    {"config", "list, register and configure pm projects",
     "pm config [-p project] [-t target] [-a name path] [-r project]", pm_config},
    {"help", "print the description and usage of each command if not specified",
     "pm help [options]", pm_help},

    {"--version", "show the current version of the pm CLI", "pm --version", pm_version},
    {NULL, NULL, NULL, NULL},
};
#define CMDC (sizeof(commands) / sizeof(commands[0]))

#define UNIMPLEMENTED							\
  printf("Function in line %d wasn't implemented yet\n", __LINE__)


/* Return the command metadata matching arg, or NULL when it is unknown. */
const Command *find_cmd(char* arg) {
  if (!arg)
    return NULL;
  for (int i = 0; commands[i].name != NULL; i++) {
    if (strcmp(arg, commands[i].name) == 0) return &commands[i];
  }
  return NULL;
}


int pm_help(int argc, char **argv) {
  if (argc == 0 || !argv) {
    for (int i = 0; commands[i].name != NULL; i++) {
      Command c = commands[i];
      printf("\nCommand: %s, usage: %s, description: %s\n", c.name, c.usage, c.description);
    }
    return EXIT_SUCCESS;
  }

  for (int i = 0; i < argc; i++) {
    bool found = false;

    for (int j = 0; commands[j].name != NULL; j++) {
      if (strcmp(commands[j].name, argv[i]) != 0)
        continue;
      Command c = commands[j];
      printf("\nCommand: %s, usage: %s, description: %s\n", c.name, c.usage, c.description);
      found = true;
      break;
    }
    if (!found)
      WARN("Command '%s' not found", argv[i]);
  }
  return EXIT_SUCCESS;
}

int pm_version(int argc, char **argv) {
  (void)argv;
  if (argc > 0) {
    WARN("This command does not accept arguments");
  }
  printf("Version: %s\n", VERSION);
  return EXIT_SUCCESS;
}

int main(int argc, char **argv) {
  if (argc < 2) {
    ERROR("A command is necessary to run pm");
    return EXIT_FAILURE;
  }

  char *command = argv[1];
  const Command *cmd = find_cmd(command);
  if (!cmd) {
    ERROR("Command '%s' not found, use the command 'help' to see other options",
          command);
    return EXIT_FAILURE;
  }

  return cmd->handler(argc - 2, argv + 2);
}
